controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

TechController:
  ros__parameters:
    type: TechControlInterface/TechController
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - position

    state_interfaces:
      - position
