controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# EtherCATController:
#   ros__parameters:
#     type: ethercat_driver/EthercatDriver
#     joints:
#       - joint2
#       - joint3
#       - joint4
#       - joint5
#       - joint6
#     command_interfaces:
#       - position
#       - velocity

#     state_interfaces:
#       - position
#       - velocity


trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint2
